*&---------------------------------------------------------------------*
*& Report ZM_NEWABAP_SYNTAX_UNION
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZM_NEWABAP_SYNTAX_UNION.

TABLES : ZBSID.

DATA : GT_BSID TYPE STANDARD TABLE OF ZBSID.

SELECT-OPTIONS :  S_BUKRS FOR ZBSID-BUKRS,
                  S_BELNR FOR ZBSID-BELNR,
                  S_GJAHR FOR ZBSID-GJAHR OBLIGATORY DEFAULT SY-DATUM+0(4).

START-OF-SELECTION.

  SELECT BUKRS BELNR GJAHR SHKZG DMBTR FROM ZBSID INTO CORRESPONDING FIELDS OF TABLE GT_BSID
    WHERE BUKRS IN S_BUKRS
    AND BELNR IN S_BELNR
    AND GJAHR IN S_GJAHR.

  SELECT BUKRS BELNR GJAHR SHKZG DMBTR FROM ZBSID APPENDING CORRESPONDING FIELDS OF TABLE GT_BSID
    WHERE BUKRS IN S_BUKRS
    AND BELNR IN S_BELNR
    AND GJAHR IN S_GJAHR.

*****************
    SELECT BUKRS, BELNR, GJAHR, SHKZG, DMBTR, 'OPEN' AS STATUS,
      CASE SHKZG WHEN 'H' THEN ( DMBTR * -1 ) ELSE DMBTR END AS AMOUNT FROM ZBSID
      WHERE BUKRS IN @S_BUKRS
      AND BELNR IN @S_BELNR
      AND GJAHR IN @S_GJAHR

    UNION ALL

    SELECT BUKRS, BELNR, GJAHR, SHKZG, DMBTR, 'CLOSE' AS STATUS,
      CASE SHKZG WHEN 'H' THEN ( DMBTR * -1 ) ELSE DMBTR END AS AMOUNT FROM ZBSID
      WHERE BUKRS IN @S_BUKRS
      AND BELNR IN @S_BELNR
      AND GJAHR IN @S_GJAHR
    INTO @DATA(GT_FI_ITEMS).

  CL_DEMO_OUTPUT=>DISPLAY( GT_BSID ).

END-OF-SELECTION.
